#!/bin/bash
#This script is created by Havard Moas, 27.01.2014 Trondheim.
#A bash script to check your LAN's connected clients against a static list with well known hosts mac adresses.
if [[ -z "$1" ]];
then
    echo -e "Please add a valid file with safe hosts.\n Example: ./checkClients safehosts.txt mymail@mydomain.com"
else
    if [[ -z "$2" ]];
    then
        echo -e "Please add a valid email address to send log from script to. \n Example ./checkClients safehosts.txt mymail@mydomain.com"
        else
	while true;
	do
	    declare -a safeList
	    let i=0
	    while IFS=$'\n' read -r line_data; do
		safeList[i]=$line_data # Populate array.
		((++i))
	    done < $1
	    
	    declare -a unknownhosts         
            let j=0
            while IFS=$'\n' read -r line_data; do
                unknownHosts[i]=$line_data # Populate array.
                ((++j))
            done < unknownhosts.txt

	    nmap -sn 192.168.2.1/24 | grep "MAC Address" | cut -d':' -f2-7 | awk -F "(" '{print $1}' | tr -d ' ' > tempfile.txt
	    declare -a checkList
	    declare -i i=0
	    while read;do
		checkList[$i]="$REPLY"
		((i = i + 1))
	    done < tempfile.txt
	    rm -r tempfile.txt
#Write to file , date and mac addresses
	    date=$(eval date)
	    for macC in "${checkList[@]}";do
		if [[ "${safeList[@]}" != *"$macC"* ]];then #Check if the host is in the safelist
		    if [[ "${unknownHosts[@]}" != *"$macC"* ]];then #Check if we already have checked it
			echo $macC >> unknownhosts.txt #Add it to the unknownhosts, so we dont get spammed with the same host
			message="A new host has just connected to your LAN:\nDate: $date\nHost Mac Address: $macC\n-------\n\nYour friendly router."
			echo -e $message | mail -a "Subject: Pia : unknownHosts - unknown host connected" $2
		    fi;
		fi;
	    done;
	    sleep 5;
	done;
    fi;
fi;

